name: Update winget deps

on: [push, workflow_dispatch, repository_dispatch]

jobs:
  update-winget:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check for updates
        uses: DeJayDev/dotfiles-action@main

